EmlakOfisi/Controllers/ResimController.cs
using EmlakOfisi.Models.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmlakOfisi.Controllers
{
    [Authorize]
    public class ResimController : Controller
    {
        Model1 ctx = new Model1();
        // GET: Resim
        public ActionResult Index()
        {
            var deger = ctx.Resimler.ToList();
            return View(deger);
        }
        [HttpGet]
        public ActionResult Ekle()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Ekle(Resimler r)
        {
            if (Request.Files.Count > 0)
            {
                string dosyaadi = Path.GetFileName(Request.Files[0].FileName);
                string uzanti=Path.GetExtension(Request.Files[0].FileName);
                string yol = "/Image/" + dosyaadi + uzanti;
                 Request.Files[0].SaveAs(Server.MapPath(yol));

                 r.OrtaYol = "/Image/" + dosyaadi + uzanti;

            }
            ctx.Resimler.Add(r);
            ctx.SaveChanges();
            return RedirectToAction("Index");




        }




    }
}

EmlakOfisi/Views/Resim/Ekle.cshtml
@using EmlakOfisi.Models.Entity;
@model EmlakOfisi.Models.Entity.Resimler
@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


<h2>Resim Ekleme Formu</h2>
<br />
<br />

@using (Html.BeginForm("Ekle", "Resim", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <p>Resim Seç</p>
    @*@Html.TextBoxFor(x => x.OrtaYol);*@
    <input type="file" name="OrtaYol"/>
    <br /><br />
    <input type="submit" value="Kaydet"/>
    
}         

EmlakOfisi/Views/Resim/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@using EmlakOfisi.Models.Entity;
@model List<Resimler>
<table class=" table table-bordered">
    <tr>
        <th>Resim ID</th>
        <th>Ortayol</th>
       
    
    </tr>
    <tbody>

        @foreach (Resimler ilan in Model)
        {
            <tr>
                <td>@ilan.ResimID</td>
                <td><img src="@ilan.OrtaYol" width="100" height="100" /></td>
                
                @*<td>@ilan.Resimler.OrtaYol</td>*@

               

            </tr>

        }



    </tbody>
</table>